import type { Product } from "./types.ts";
import food from "../../../assets/food.jpg"

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 2,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 3,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 4,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 5,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 6,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 7,
    name: "Grill Sandwich",
    status: "Out of Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
];