import type { Product, Customer, WalletRecord } from "./types.ts";
import food from "../../assets/food.jpg";
import user from "../../assets/user.jpg";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 2,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 3,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 4,
    name: "Grill Sandwich",
    status: "Out of Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 5,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 6,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 7,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: "Ravinder Bhatia",
    employeeId: "3830",
    email: "BhatiaRavinder@bugraptors.com",
    orders: 12,
    pendingBill: 1147,
    wallet: 0,
    gender: "Male",
    address: "12 Oak Lane",
    image: user,
  },
  {
    id: 2,
    name: "Shivam Kaul",
    employeeId: "3885",
    email: "KaulShivam@seasiainfotech.com",
    orders: 8,
    pendingBill: 1083,
    wallet: 0,
    gender: "Male",
    address: "45 Maple Street",
    image: user,
  },
  {
    id: 3,
    name: "Dipesh Kumar",
    employeeId: "3509",
    email: "kumardipesh@seasiainfotech.com",
    orders: 15,
    pendingBill: 991,
    wallet: 0,
    gender: "Male",
    address: "78 Pine Avenue",
    image: user,
  },
  {
    id: 4,
    name: "Rajbir Singh",
    employeeId: "4003",
    email: "singhrajbir@seasiaconnect.com",
    orders: 5,
    pendingBill: 988,
    wallet: 0,
    gender: "Male",
    address: "23 Cedar Road",
    image: user,
  },
  {
    id: 5,
    name: "Gurkirat Bawa Gary",
    employeeId: "2075",
    email: "gbawa@seasiainfotech.com",
    orders: 20,
    pendingBill: 857,
    wallet: 0,
    gender: "Male",
    address: "56 Birch Boulevard",
    image: user,
  },
  {
    id: 6,
    name: "Ramtirth Mallick",
    employeeId: "3810",
    email: "Mallickramtirth@seasiaconnect.com",
    orders: 3,
    pendingBill: 652,
    wallet: 0,
    gender: "Male",
    address: "90 Elm Court",
    image: user,
  },
  {
    id: 7,
    name: "Rajnish Narayan Singh",
    employeeId: "3795",
    email: "singhrajnish@seasiainfotech.com",
    orders: 9,
    pendingBill: 850,
    wallet: 0,
    gender: "Male",
    address: "34 Willow Way",
    image: user,
  },
  {
    id: 8,
    name: "Harsha Kapila",
    employeeId: "3452",
    email: "kapilaharsha@seasiainfotech.com",
    orders: 7,
    pendingBill: 797,
    wallet: 0,
    gender: "Female",
    address: "67 Spruce Drive",
    image: user,
  },
  {
    id: 9,
    name: "Varun Kumar",
    employeeId: "3474",
    email: "kumarvarun@seasiainfotech.com",
    orders: 11,
    pendingBill: 795,
    wallet: 0,
    gender: "Male",
    address: "11 Aspen Place",
    image: user,
  },
  {
    id: 10,
    name: "Anmol Kumar",
    employeeId: "3778",
    email: "kumaranmol@seasiainfotech.com",
    orders: 6,
    pendingBill: 600,
    wallet: 0,
    gender: "Male",
    address: "88 Poplar Street",
    image: user,
  },
];

export const WALLET_DATA: WalletRecord[] = [
  {
    id: 1,
    employeeName: "Jagdev Singh",
    payment: 1000,
    walletBalance: 0,
    date: "02-19-2026",
    time: "11:29:44 am",
  },
  {
    id: 2,
    employeeName: "Sehjot Singh",
    payment: 250,
    walletBalance: 250,
    date: "02-18-2026",
    time: "02:08:52 pm",
  },
  {
    id: 3,
    employeeName: "Anmol Kumar",
    payment: 1000,
    walletBalance: 0,
    date: "02-18-2026",
    time: "10:59:28 am",
  },
  {
    id: 4,
    employeeName: "Harshit Sharma",
    payment: 500,
    walletBalance: 225,
    date: "02-18-2026",
    time: "10:47:39 am",
  },
  {
    id: 5,
    employeeName: "Jasdeep Singh",
    payment: 2000,
    walletBalance: 711,
    date: "02-18-2026",
    time: "10:15:53 am",
  },
  {
    id: 6,
    employeeName: "Pardeep Kumar",
    payment: 500,
    walletBalance: 0,
    date: "02-18-2026",
    time: "10:07:11 am",
  },
  {
    id: 7,
    employeeName: "Saurav Sharma",
    payment: 500,
    walletBalance: 478,
    date: "02-18-2026",
    time: "10:06:57 am",
  },
  {
    id: 8,
    employeeName: "Raghav Rallan",
    payment: 1500,
    walletBalance: 285,
    date: "02-17-2026",
    time: "01:52:47 pm",
  },
  {
    id: 9,
    employeeName: "Rajnish Narayan Singh",
    payment: 1100,
    walletBalance: 0,
    date: "02-17-2026",
    time: "01:52:39 pm",
  },
  {
    id: 10,
    employeeName: "Raghav Goel",
    payment: 1000,
    walletBalance: 1070,
    date: "02-17-2026",
    time: "01:23:43 pm",
  },
];