import type { Product, Customer } from "./types.ts";
import food from "../../assets/food.jpg";
import user from "../../assets/user.jpg";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 2,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 3,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 4,
    name: "Grill Sandwich",
    status: "Out of Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
  {
    id: 5,
    name: "Chicken Popeyes",
    status: "In Stock",
    productId: "67869052",
    quantity: 40,
    price: 30,
    unit: "piece",
    category: "Chicken",
    image: food,
  },
  {
    id: 6,
    name: "Bison Burgers",
    status: "In Stock",
    productId: "68970163",
    quantity: 40,
    price: 40,
    unit: "piece",
    category: "Burger",
    image: food,
  },
  {
    id: 7,
    name: "Grill Sandwich",
    status: "In Stock",
    productId: "66758941",
    quantity: 50,
    price: 20,
    unit: "piece",
    category: "Sandwich",
    image: food,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: "Addie Minstra",
    orders: 250,
    spent: 3500,
    gender: "Male",
    address: "2603 Jadewood Drive",
    image: user,
  },
  {
    id: 2,
    name: "Manuel Labor",
    orders: 300,
    spent: 4800,
    gender: "Male",
    address: "3799 Glendale Avenue",
    image: user,
  },
  {
    id: 3,
    name: "Jack Arnanda",
    orders: 260,
    spent: 2800,
    gender: "Male",
    address: "8270 Wildwood Street",
    image: user,
  },
  {
    id: 4,
    name: "Staum Cliowd",
    orders: 450,
    spent: 3800,
    gender: "Male",
    address: "5056 Lindgren Village",
    image: user,
  },
  {
    id: 5,
    name: "Addie Minstra",
    orders: 250,
    spent: 3500,
    gender: "Male",
    address: "2603 Jadewood Drive",
    image: user,
  },
  {
    id: 6,
    name: "Manuel Labor",
    orders: 300,
    spent: 6800,
    gender: "Male",
    address: "3799 Glendale Avenue",
    image: user,
  },
  {
    id: 7,
    name: "Jack Arnanda",
    orders: 260,
    spent: 2800,
    gender: "Male",
    address: "8270 Wildwood Street",
    image: user,
  },
  {
    id: 8,
    name: "Staum Cliowd",
    orders: 450,
    spent: 3800,
    gender: "Male",
    address: "5056 Lindgren Village",
    image: user,
  },
];
